---
# Title: app-win-template
#
# Author: Luc Rutten
# File: tasks/main.yml
#
# Description:
#   Check if application allready is installed.

- name: "Check if package is already installed before downloading installation files. (64bit)"
  win_reg_stat:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{{ pkg_product_id }}'
  register: pkg_isinstalled

- name: "Print if app is installed"
  debug:
    msg: "{{ pkg_isinstalled }}"

- name: "import tasks/install"
  import_tasks: install.yml
  when:
    - pkg_isinstalled.exists == false
