---
# Title: app-win-template
#
# Author: Luc Rutten
# File: tasks/install.yml
#
# Description: 
#   Install Windows package on Endpoint


- name: "Create local Ansible repository"
  win_file:
    path: "{{ pkg_repo_local }}"
    state: directory

- name: "Download Package"
  win_get_url:
    url: "{{ pkg_repo_remote }}"
    dest: "{{ pkg_repo_local }}\\{{ pkg_name }}.zip"
    force: no

- name: "Unzip package"
  win_unzip:
    src: "{{ pkg_repo_local }}\\{{ pkg_name }}.zip"
    dest: "{{ pkg_repo_local }}"

- name: "Installing {{ pkg_name }}"
  win_package:
    path: "{{ pkg_installer }}"
    product_id: "{{ pkg_product_id }}"
    arguments: "{{ pkg_arguments }}"
    state: present

- name: "Removing installation files"
  win_file:
    path: "{{ pkg_repo_local }}"
    state: absent

